name: Update Dependencies
on:
  schedule:
    - cron: '15 15 * * 3'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Update dependencies
        run: |
          tox -e upgrade
      - name: Create commits
        run: |
          git config user.name 'pip-compile-multi'
          git config user.email 'pip-compile-multi@users.noreply.github.com'
          git commit -am "Update dependencies"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
            token: ${{ secrets.PAT }}
            title: Update dependencies
            body: |
              Auto-generated by [pip-compile-multi](https://github.com/peterdemin/pip-compile-multi)
            branch: update-dependencies
            branch-suffix: timestamp
